name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.1
  http: ^0.13.5
  lottie: ^2.0.0
  google_fonts: ^4.0.3
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  shaders:
    - shaders/orb.frag
    - shaders/iridescence.frag
